## Sends a slack message
## Docs: 
## * https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges
##
name: "auto-southwest-check-in-gar"

# on:
#   # Push is for testing only to allow you to test this workflow without
#   # a merge and just a push.
#   push:
#   pull_request:
#     types:
#       - closed

on:
  # Push is for testing only to allow you to test this workflow without
  # a merge and just a push.
#   push:
  pull_request:
    # types:
    #   - closed
    # branches:
    #   - main

  ## Schedule doc: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
          ## ┌───────────── minute (0 - 59)
          ## │  ┌───────────── hour (0 - 23)
          ## │  │ ┌───────────── day of the month (1 - 31)
          ## │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
          ## │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
          ## │  │ │ │ │
          ## │  │ │ │ │
          ## │  │ │ │ │
          ## *  * * * *
    - cron: '37 10 * * *'
    - cron: '37 12 * * *'

env:
  # SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  # SLACK_CHANNEL: 'C05B9LLPVD5' # sf-devops.slack.com - recreation-gov

  # Enable debug output
  DEBUG: false

jobs:
  check_open_reservations:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    ## Set the max time to run this job
    ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
    timeout-minutes: 180
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |
        cd soutthwest.com/auto-southwest-check-in/auto-southwest-check-in
        pip3 install -r requirements.txt
        python3 southwest.py --verbose ${{ secrets.SOUTHWEST_USER_NAME_GAR }} ${{ secrets.SOUTHWEST_PASSWORD_GAR }}
