## Sends a slack message
## Docs: 
## * https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges
##
name: "auto-southwest-check-in-gar"

# on:
#   # Push is for testing only to allow you to test this workflow without
#   # a merge and just a push.
#   push:
#   pull_request:
#     types:
#       - closed

on:
  # Push is for testing only to allow you to test this workflow without
  # a merge and just a push.
#   push:
  pull_request:
    # types:
    #   - closed
    # branches:
    #   - main

  ## Schedule doc: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  # schedule:
  #   - cron: '*/5 * * * *'

env:
  # SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  # SLACK_CHANNEL: 'C05B9LLPVD5' # sf-devops.slack.com - recreation-gov

  # Enable debug output
  DEBUG: false

jobs:
  check_open_reservations:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |
        cd soutthwest.com/auto-southwest-check-in/auto-southwest-check-in
        pip3 install -r requirements.txt
        python3 southwest.py --verbose ${{ secrets.SOUTHWEST_USER_NAME_GAR }} ${{ secrets.SOUTHWEST_PASSWORD_GAR }}
