## Sends a slack message
## Docs: 
## * https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges
##
name: "Slack - rec.gov - tours"

# on:
#   # Push is for testing only to allow you to test this workflow without
#   # a merge and just a push.
#   push:
#   pull_request:
#     types:
#       - closed

on:
  # Push is for testing only to allow you to test this workflow without
  # a merge and just a push.
#   push:
  pull_request:
    # types:
    #   - closed
    # branches:
    #   - main

# env:
#   SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}

jobs:
  send_slack:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        AVAILABLE_DATES=$(./recreation-gov/run.sh 233362 502 2023 06)

        echo "AVAILABLE_DATES=$AVAILABLE_DATES" >> $GITHUB_ENV
      env:
        JSON_OUTPUT_EVENT_PULL_REQUEST: ${{ toJSON(github.event.pull_request) }}

    ## Doc: https://github.com/marketplace/actions/slack-send
    - name: Post to Slack channel
      id: slack1
      uses: slackapi/slack-github-action@v1.24.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
        channel-id: 'C05B9LLPVD5' # sf-devops.slack.com - recreation-gov
        # For posting a simple plain text message
        # Slack message format: <github repo name> | <github user> | <PR Title> | <PR URL>
        slack-message: | 
          ${{ env.AVAILABLE_DATES }}
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}